#!/usr/bin/env bash

set -e
set -u
set -o pipefail

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

git config --global user.email "donal@bluedrop.com"
git config --global user.name "Donal Mac An Ri"

# Check for Homebrew
if ! command -v brew &> /dev/null
then
	printf "Installing Homebrew\n"
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null | tee /tmp/homebrew-install.log
else
	read -r -p 'Should I update your Homebrew install? [y/N] ' response
	if [[ "${response}" =~ ^[yY](es)*$ ]]
	then
		brew update
	fi
fi

# install brew bundle
brew tap Homebrew/bundle

./install

ln -s "${dir}/zshrc" "${HOME}/.zshrc"
ln -s "${dir}/emacs.d" "${HOME}/.emacs.d"
