#!/bin/bash

set -e
set -u
set -o pipefail

sshdir=${HOME}/.ssh

# 1password credentials
secret_key="A3-34TLZQ-HEWL7R-XB46G-4JZMJ-LSJX5-VPKFF"
email="donalmacanri@bluedrop.com"
account="bluedrop"

session_token=$(op signin $account $email $secret_key --output=raw)

mkdir -p $sshdir

# copy personal ssh key from 1password
item_json=$(echo $session_token | \
    op get item "id_rsa @donal" | \
    jq -r .details)

# read private key from notes field
echo $item_json | jq -r .notesPlain > $sshdir/id_rsa

chmod 600 $sshdir/id_rsa

# get reference to linked document labelled "id_rsa.pub"
pubkey_doc=$(echo $item_json | \
    jq -r '.sections[0].fields | map(select(.t == "id_rsa.pub")) | .[0].v')

# get public key document
echo $session_token | \
    op get document $pubkey_doc > $sshdir/id_rsa.pub
